[tasks.create-keypair]
condition.env_true = ['CARGO_MAKE_TASK_ENABLE_SETUP_PROJECT_CREATE_KEYPAIR']
condition.files_not_exist = [
  "${CARGO_MAKE_WORKING_DIRECTORY}/config.development/bff/key.pem",
  "${CARGO_MAKE_WORKING_DIRECTORY}/config.development/bff/pubkey.pem"
]
dependencies = [
  "prepare"
]
script = [
'''
openssl genrsa -out config.development/bff/key.pem 4096
openssl rsa -in config.development/bff/key.pem -pubout -out config.development/bff/pubkey.pem
'''
]
