[tasks.generate-secret]
condition.env_true = ['CARGO_MAKE_TASK_ENABLE_SETUP_PROJECT_GENERATE_SECRET']
condition.files_not_exist = [
  "${CARGO_MAKE_WORKING_DIRECTORY}/config.development/bff/secret.txt"
]
dependencies = [
  "prepare"
]
script = [
'''
openssl rand -base64 32 > config.development/bff/secret.txt
'''
]
