extend = [
  { path = ".setup-project.create-config-files.toml" },
  { path = ".setup-project.create-dotenv-file.toml" },
  { path = ".setup-project.generate-keypair.toml" },
  { path = ".setup-project.generate-secret.toml" },
  { path = ".setup-project.place-google-cloud-keyfile.toml" }
]

[config]
skip_core_tasks = true
min_version = "0.26.1"

[tasks.prepare]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../"

[tasks.default]
dependencies = [
  "generate-keypair",
  "generate-secret",
  "place-google-cloud-keyfile",
  "create-dotenv-file",
  "create-config-files"
]
