extend = [
  { path = ".setup-project.create-dotenv-file.toml" },
  { path = ".setup-project.place-google-cloud-keyfile.toml" }
]

[config]
skip_core_tasks = true
min_version = "0.26.1"

[tasks.prepare]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../"

[tasks.default]
run_task = [
  { name = "place-google-cloud-keyfile" },
  { name = "create-dotenv-file" }
]
